"""empty message

Revision ID: 536611d588d6
Revises: 38f808ce4c9a
Create Date: 2024-11-04 10:47:49.817601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536611d588d6'
down_revision = '38f808ce4c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
