"""empty message

Revision ID: 613c7c264225
Revises: 536611d588d6
Create Date: 2024-11-04 11:43:52.957262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613c7c264225'
down_revision = '536611d588d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
