"""empty message

Revision ID: 81c4df8b681e
Revises: 613c7c264225
Create Date: 2024-11-04 15:56:42.152800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c4df8b681e'
down_revision = '613c7c264225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('event_venue', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('date')
        batch_op.drop_column('description')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('event_time')
        batch_op.drop_column('event_venue')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_name')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
